name: Trump Course
favicon: null
layout_spectrum: 0.24348
typography_spectrum: 0.8790726866573095
title: A Course on Lessons to Be Learned From The Trump Campaign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2d2e28'
    - '#9e8863'
    - '#fbd8bc'
    - '#7f5329'
  brandStrength: 0.5
  lightness: 0.2610046030022204
  saturation: 0.05117073468863964
  rhythmicContrast: 0.5356561995577067
purpose: []
